# Basic Python

## Split this string

In [1]:
s = "What the hell!"

In [2]:
s.split()

['What', 'the', 'hell!']

## Use .format() to print the following string. 


In [48]:
shape = "Circle"
circumferance = '2πr'

In [49]:
print("The circumferance of a {} is {}.".format(shape,circumferance))

The circumferance of a Circle is 2πr.


## In this nest dictionary grab the word "hello"

In [25]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [26]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [27]:
import numpy as np

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Create an array of all the odd integers from 2 to 50

In [29]:
np.arange(2,50,1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Create a 3x3 matrix

In [32]:
np.arange(31,40).reshape(3,3)

array([[31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

## Concatination

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## Create a dataframe

In [46]:
import pandas as pd
df = pd.DataFrame({"Name":['Vetri','Nithin','Suresh'],"Grade":['A', 'B', 'A+']})#object

In [42]:
print(df)

     Name Grade
0   Vetri     A
1  Nithin     B
2  Suresh    A+


## Generate the series of dates

In [36]:
np.arange('2001-01-01','2002-02-10',dtype='datetime64[D]')

array(['2001-01-01', '2001-01-02', '2001-01-03', '2001-01-04',
       '2001-01-05', '2001-01-06', '2001-01-07', '2001-01-08',
       '2001-01-09', '2001-01-10', '2001-01-11', '2001-01-12',
       '2001-01-13', '2001-01-14', '2001-01-15', '2001-01-16',
       '2001-01-17', '2001-01-18', '2001-01-19', '2001-01-20',
       '2001-01-21', '2001-01-22', '2001-01-23', '2001-01-24',
       '2001-01-25', '2001-01-26', '2001-01-27', '2001-01-28',
       '2001-01-29', '2001-01-30', '2001-01-31', '2001-02-01',
       '2001-02-02', '2001-02-03', '2001-02-04', '2001-02-05',
       '2001-02-06', '2001-02-07', '2001-02-08', '2001-02-09',
       '2001-02-10', '2001-02-11', '2001-02-12', '2001-02-13',
       '2001-02-14', '2001-02-15', '2001-02-16', '2001-02-17',
       '2001-02-18', '2001-02-19', '2001-02-20', '2001-02-21',
       '2001-02-22', '2001-02-23', '2001-02-24', '2001-02-25',
       '2001-02-26', '2001-02-27', '2001-02-28', '2001-03-01',
       '2001-03-02', '2001-03-03', '2001-03-04', '2001-

## Create 2D list to DataFrame


In [34]:
lists = [[1, 2, 3], [11, 22, 33], [111, 222, 333]]

In [35]:
df = pd.DataFrame(lists)
print(df)

     0    1    2
0    1    2    3
1   11   22   33
2  111  222  333
